version: '3.1'

services:
  app:
    build: .
    env_file:
      - .env
    environment:
      PORT: 443
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_NAME: fake_store
      DB_PORT: 27017
      DATABASE_URL: mongodb://$DB_USERNAME:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?authSource=admin

    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    volumes:
      - ./mongo_data:/data/db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME?MongoDB username}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD?MongoDB password}
